version: '3.7'
services:
  ca-mfd-prc-andon:
    image: eql-yum.eq2iqm.com/changanmes/ca-mfd-prc-andon-service:0930
    container_name: ca-mfd-prc-andon-service
    volumes:
      - /home/logs/ca-mfd-prc-andon:/tmp
    ports:
      - "19104:19104"
    environment:
      TZ: "Asia/Shanghai"
      CAS_ENV: "testing"
      PAAS_CSE_SC_ENDPOINT: "http://10.23.1.142:30100"
      PAAS_CSE_CC_ENDPOINT: "http://10.23.1.142:30110"
    deploy:
      resources:
        limits:
          memory: 1G

  ca-mfd-prc-avi:
    image: eql-yum.eq2iqm.com/changanmes/ca-mfd-prc-avi-service:0930
    container_name: ca-mfd-prc-avi-service
    volumes:
      - /home/logs/ca-mfd-prc-avi:/tmp
    ports:
      - "19110:19110"
    environment:
      TZ: "Asia/Shanghai"
      CAS_ENV: "testing"
      PAAS_CSE_SC_ENDPOINT: "http://10.23.1.142:30100"
      PAAS_CSE_CC_ENDPOINT: "http://10.23.1.142:30110"
    deploy:
      resources:
        limits:
          memory: 1G

  ca-mfd-prc-pmc:
    image: eql-yum.eq2iqm.com/changanmes/ca-mfd-prc-pmc-service:0930
    container_name: ca-mfd-prc-pmc-service
    volumes:
      - /home/logs/ca-mfd-prc-pmc:/tmp
    ports:
      - "19120:19120"
    environment:
      TZ: "Asia/Shanghai"
      CAS_ENV: "testing"
      PAAS_CSE_SC_ENDPOINT: "http://10.23.1.142:30100"
      PAAS_CSE_CC_ENDPOINT: "http://10.23.1.142:30110"
    deploy:
      resources:
        limits:
          memory: 1G

  ca-mfd-prc-pps:
    image: eql-yum.eq2iqm.com/changanmes/ca-mfd-prc-pps-service:0930
    container_name: ca-mfd-prc-pps-service
    volumes:
      - /home/logs/ca-mfd-prc-pps:/tmp
    ports:
      - "19122:19122"
    environment:
      TZ: "Asia/Shanghai"
      CAS_ENV: "testing"
      PAAS_CSE_SC_ENDPOINT: "http://10.23.1.142:30100"
      PAAS_CSE_CC_ENDPOINT: "http://10.23.1.142:30110"
    deploy:
      resources:
        limits:
          memory: 1G

  ca-mfd-prc-pqs:
    image: eql-yum.eq2iqm.com/changanmes/ca-mfd-prc-pqs-service:0930
    container_name: ca-mfd-prc-pqs-service
    volumes:
      - /home/logs/ca-mfd-prc-pqs:/tmp
    ports:
      - "19123:19123"
    environment:
      TZ: "Asia/Shanghai"
      CAS_ENV: "testing"
      PAAS_CSE_SC_ENDPOINT: "http://10.23.1.142:30100"
      PAAS_CSE_CC_ENDPOINT: "http://10.23.1.142:30110"
    deploy:
      resources:
        limits:
          memory: 1G

  ca-mfd-quc-qps:
    image: eql-yum.eq2iqm.com/changanmes/ca-mfd-quc-qps-service:0930
    container_name: ca-mfd-quc-qps-service
    volumes:
      - /home/logs/ca-mfd-quc-qps:/tmp
    ports:
      - "19194:19194"
    environment:
      TZ: "Asia/Shanghai"
      CAS_ENV: "testing"
      PAAS_CSE_SC_ENDPOINT: "http://10.23.1.142:30100"
      PAAS_CSE_CC_ENDPOINT: "http://10.23.1.142:30110"
    deploy:
      resources:
        limits:
          memory: 1G

  ca-mfd-prc-pm:
    image: eql-yum.eq2iqm.com/changanmes/ca-mfd-prc-pm-service:0930
    container_name: ca-mfd-prc-pm-service
    volumes:
      - /home/logs/ca-mfd-prc-pm:/tmp
    ports:
      - "19118:19118"
    environment:
      TZ: "Asia/Shanghai"
      CAS_ENV: "testing"
      PAAS_CSE_SC_ENDPOINT: "http://10.23.1.142:30100"
      PAAS_CSE_CC_ENDPOINT: "http://10.23.1.142:30110"
    deploy:
      resources:
        limits:
          memory: 1G

  ca-mfd-prc-core:
    image: eql-yum.eq2iqm.com/changanmes/ca-mfd-prc-core-service:0930
    container_name: ca-mfd-prc-core-service
    volumes:
      - /home/logs/ca-mfd-prc-core:/tmp
      - /home/fs:/fs
    ports:
      - "19103:19103"
    environment:
      TZ: "Asia/Shanghai"
      CAS_ENV: "testing"
      PAAS_CSE_SC_ENDPOINT: "http://10.23.1.142:30100"
      PAAS_CSE_CC_ENDPOINT: "http://10.23.1.142:30110"
    deploy:
      resources:
        limits:
          memory: 1G

  ca-mfd-prc-gateway:
    image: eql-yum.eq2iqm.com/changanmes/ca-mfd-prc-gateway:0930
    container_name: ca-mfd-prc-gateway
    volumes:
      - /home/logs/ca-mfd-prc-gateway:/tmp
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Shanghai"
      CAS_ENV: "testing"
      PAAS_CSE_SC_ENDPOINT: "http://10.23.1.142:30100"
      PAAS_CSE_CC_ENDPOINT: "http://10.23.1.142:30110"
    deploy:
      resources:
        limits:
          memory: 1G

  ca-mfd-prc-eps:
    image: eql-yum.eq2iqm.com/changanmes/ca-mfd-prc-eps-service:0930
    container_name: ca-mfd-prc-eps-service
    volumes:
      - /home/logs/ca-mfd-prc-eps:/tmp
    ports:
      - "19113:19113"
    environment:
      TZ: "Asia/Shanghai"
      CAS_ENV: "testing"
      PAAS_CSE_SC_ENDPOINT: "http://10.23.1.142:30100"
      PAAS_CSE_CC_ENDPOINT: "http://10.23.1.142:30110"
    deploy:
      resources:
        limits:
          memory: 1G

  ca-mfd-prc-rc:
    image: eql-yum.eq2iqm.com/changanmes/ca-mfd-prc-rc-service:0930
    container_name: ca-mfd-prc-rc-service
    volumes:
      - /home/logs/ca-mfd-prc-rc:/tmp
    ports:
      - "19142:19142"
    environment:
      TZ: "Asia/Shanghai"
      CAS_ENV: "testing"
      PAAS_CSE_SC_ENDPOINT: "http://10.23.1.142:30100"
      PAAS_CSE_CC_ENDPOINT: "http://10.23.1.142:30110"
    deploy:
      resources:
        limits:
          memory: 1G

  ca-mfd-prc-bdc:
    image: eql-yum.eq2iqm.com/changanmes/ca-mfd-prc-bdc-service:0930
    container_name: ca-mfd-prc-bdc-service
    volumes:
      - /home/logs/ca-mfd-prc-bdc:/tmp
    ports:
      - "19193:19193"
    environment:
      TZ: "Asia/Shanghai"
      CAS_ENV: "testing"
      PAAS_CSE_SC_ENDPOINT: "http://10.23.1.142:30100"
      PAAS_CSE_CC_ENDPOINT: "http://10.23.1.142:30110"
    deploy:
      resources:
        limits:
          memory: 1G

  ca-mfd-prc-scheduler:
    image: eql-yum.eq2iqm.com/changanmes/ca-mfd-prc-scheduler-service:0930
    container_name: ca-mfd-prc-scheduler-service
    volumes:
      - /home/logs/ca-mfd-prc-scheduler:/tmp
    ports:
      - "19149:19149"
    environment:
      TZ: "Asia/Shanghai"
    deploy:
      resources:
        limits:
          memory: 2G

  ca-mfd-cmc-pm:
    image: eql-yum.eq2iqm.com/changanmes/ca-mfd-cmc-pm-service:0930
    container_name: ca-mfd-cmc-pm-service
    volumes:
      - /home/logs/ca-mfd-cmc-pm:/tmp
    ports:
      - "19200:19200"
    environment:
      TZ: "Asia/Shanghai"
      CAS_ENV: "testing"
      PAAS_CSE_SC_ENDPOINT: "http://10.23.1.142:30100"
      PAAS_CSE_CC_ENDPOINT: "http://10.23.1.142:30110"
    deploy:
      resources:
        limits:
          memory: 1G

  ca-mfd-prc-audit:
    image: eql-yum.eq2iqm.com/changanmes/ca-mfd-prc-audit-service:0930
    container_name: ca-mfd-prc-audit-service
    volumes:
      - /home/logs/ca-mfd-prc-audit:/tmp
    ports:
      - "19195:19195"
    environment:
      TZ: "Asia/Shanghai"
      CAS_ENV: "testing"
      PAAS_CSE_SC_ENDPOINT: "http://10.23.1.142:30100"
      PAAS_CSE_CC_ENDPOINT: "http://10.23.1.142:30110"
    deploy:
      resources:
        limits:
          memory: 2G